"""Route every coding agent to the shared workflows in .claude/ (the single source).

    python tools/agents/run.py          # rewrite the routers
    python tools/agents/run.py --check  # exit 1 when a router is stale (the tests run this)

Source: CLAUDE.md (project rules) and .claude/skills/<name>/SKILL.md (workflows). Generated routers:
AGENTS.md (Codex and other AGENTS.md readers), .github/copilot-instructions.md (GitHub Copilot) and
.cursor/rules/spritemotion.mdc (Cursor). Edit the source, then run this; never edit a router by hand.
"""
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
BEGIN, END = '<!-- skills:begin (generated by tools/agents/run.py) -->', '<!-- skills:end -->'


def skills():
    rows = []
    for path in sorted((REPO / '.claude' / 'skills').glob('*/SKILL.md')):
        head = re.match(r'---\n(.*?)\n---', path.read_text(encoding='utf-8'), re.S)
        meta = dict(line.split(':', 1) for line in head.group(1).splitlines() if ':' in line) if head else {}
        rows.append((meta.get('name', path.parent.name).strip(), meta.get('description', '').strip(), path.relative_to(REPO).as_posix()))
    return rows


def body():
    lines = [BEGIN, '', '| Skill | Use it when | Instructions |', '|---|---|---|']
    lines += [f'| `{n}` | {d} | [{p}]({p}) |' for n, d, p in skills()]
    return '\n'.join(lines + ['', END])


INTRO = """# Agent instructions

This repository keeps its agent instructions in **`.claude/`**, shared by every coding agent (Claude Code, Codex,
Cursor, Copilot and others). Before working:

1. Read [`CLAUDE.md`](CLAUDE.md): the project rules. They apply to you whatever agent you are.
2. When a task matches a skill below, open its `SKILL.md` and follow it as your procedure.

"""
TARGETS = {
    'AGENTS.md': INTRO,
    '.github/copilot-instructions.md': INTRO,
    '.cursor/rules/spritemotion.mdc': '---\ndescription: SpriteMotion project rules and workflows (source: CLAUDE.md and .claude/skills)\nalwaysApply: true\n---\n\n' + INTRO,
}


def render(intro): return intro + body() + '\n'


def main():
    stale = []
    for rel, intro in TARGETS.items():
        path = REPO / rel; text = render(intro)
        if '--check' in sys.argv:
            if not path.exists() or path.read_text(encoding='utf-8') != text: stale.append(rel)
        else:
            path.parent.mkdir(parents=True, exist_ok=True); path.write_text(text, encoding='utf-8', newline='\n')
    if stale: sys.exit('Stale agent routers (run python tools/agents/run.py): ' + ', '.join(stale))
    print('agent routers up to date' if '--check' in sys.argv else f'wrote {len(TARGETS)} routers, {len(skills())} skills')


if __name__ == '__main__':
    main()
